# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af6f167b2a06e2381b61d2484fe31fe77788909c59838dbad965f63f835133b61729ff43ffea19fe14c6d1af8cea1cc306ce5089bba6a25b48d0702163f55db5

test:
  secret_key_base: ba3b00135f073b62ef034ab0df4f723143f6085513966ba4951a6a28e012c3501857a62d30661e4a7bbefa7f6b8116fbafba394ca451d419ecc871f085383982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
